config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  root to: 'site#index'
  devise_for :users, controllers: {passwords: "users/passwords", sessions: "users/sessions", registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/users/index', to: 'users#index', as: "user_index"
  get '/users/edit_profile', to: 'users#edit', as: "edit_user"
  patch '/users/edit_profile', to: 'users#update', as: ""
  put '/users/edit_profile', to: 'users#update', as: ""
  resources :relationships, only: [:create]
  patch '/relationships', to: 'relationships#update', as: ""
  put '/relationships', to: 'relationships#update', as: ""
  delete '/relationships', to: 'relationships#destroy', as: ""
  
  put '/relationships/message_now', to: 'relationships#message_now', as: "relationship_message_now"
  patch '/relationships/message_now', to: 'relationships#message_now', as: ""

  put '/relationships/twitter_friends', to: 'relationships#twitter_friends', as: "twitter_friends"
  patch '/relationships/twitter_friends', to: 'relationships#twitter_friends', as: ""

  put '/relationships/user_messages', to: 'relationships#user_messages', as: "user_messages"
  patch '/relationships/user_message', to: 'relationships#user_messages', as: ""

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :relationships_association, :class_name => "Relationship"
  has_many :relationships
  # ,:through => :relationships_association, :source => :relationship
  # has_many :inverse_relationships_association, :class_name => "Relationship", :foreign_key => "relationship_id"
  # has_many :inverse_relationships, :through => :inverse_relationships_association, :source => :user
  has_many :social_networks, inverse_of: :user
  has_many :inverse_social_networks
  accepts_nested_attributes_for :relationships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :omniauthable, :omniauth_providers => [:facebook, :twitter, :google_oauth2]  

  def self.persona_mail_exists?(email)
    User.find_by!(email: email).present?
    rescue ActiveRecord::RecordNotFound
      return false
  end

  def self.persona_signed_up?(email)
    User.find_by!(email: email).encrypted_password.present?
    rescue ActiveRecord::RecordNotFound
      return false
  end

  def self.what_persona_id?(email)
    User.find_by(email: email).id
  end

  def self.persona_find_or_create(*args)
    uid = args[0] || 0
    email = args[1] || ""
    name = args[2] || ""
    surname = args[3] || ""
    
    if SocialNetwork.social_network_uid_exists?(uid)
      SocialNetwork.what_social_network_user_id?(uid)
    
    else
      User.create_with(name: name,surname: surname).find_or_create_by(email: email).id
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    auth = request.env["omniauth.auth"]
    if user_signed_in?
      id = current_user.id
    else
      name = auth.info.first_name || auth.info.name.split[0] || ""
      sirname = auth.info.last_name || auth.info.name.split[1..-1].join(" ") || "" 
      id = User.persona_find_or_create(auth.uid,auth.info.email,name, sirname)
    end

    @user = SocialNetwork.from_omniauth_fb(id,auth)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to show_user_registration_path
    end
  end

  def twitter
    auth = request.env["omniauth.auth"]
    if user_signed_in?
      id = current_user.id
    else
      name = auth.info.first_name || auth.info.name.split[0] || ""
      sirname = auth.info.last_name || auth.info.name.split[1..-1].join(" ") || "" 
      id = User.persona_find_or_create(auth.uid,auth.info.email,name, sirname)
    end

    @user = SocialNetwork.from_omniauth_tw(id,auth)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to show_user_registration_path
    end
  end

  def google_oauth2
    auth = request.env["omniauth.auth"]
    if user_signed_in?
      id = current_user.id
    else
      name = auth.info.first_name || auth.info.name.split[0] || ""
      sirname = auth.info.last_name || auth.info.name.split[1..-1].join(" ") || "" 
      id = User.persona_find_or_create(auth.uid,auth.info.email,name, sirname)
    end

    @user = SocialNetwork.from_omniauth_gg(id,auth)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "google_oauth2") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to show_user_registration_path
    end
  end

  def failure
    redirect_to root_path
  end

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_filter :configure_sign_up_params, only: [:create]
 before_filter :configure_account_update_params, only: [:update]
 include UsersHelper

  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
   def edit
     super
   end

  # PUT /resource
   def update
     super
   end

  # DELETE /resource
   def destroy
    user_unsign_up
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    flash[:notice] = "Account succesfully cancelled"
    redirect_to root_path
    # yield resource if block_given?
    # respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
   end


  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
   def cancel
     super
   end

  protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.for(:sign_up) << :bday
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.for(:account_update) << [:bday, :name, :sirname, :city, :country, :gender]
   end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     "/users/index"
   end

  # The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
     super(resource)
   end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :attribute
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

	def index
		@user_active_networks = get_user_active_networks(current_user)
		@relationship = Relationship.new
		@message = Message.new
		@months = I18n.t :"date.month_names", locale: :es

	end

	def edit
		
	end

	def update
	      if current_user.update_attributes(user_params)
	        redirect_to action: 'index', notice: 'User was successfully updated.'
	      else
	        render :edit, notice: 'User could not be updated'
	      end
	end

private
	def user_params
      params.require(:user).permit(:name, :surname, :email, :bday, :city, :country, :language, :gender)
    end

    def get_user_active_networks(user)
    	networks = existing_networks
    	user_networks = get_user_networks (user)
    	networks.each do |network,value|
    		if user_networks.include?(network.to_s)
    			networks[network]=true    		
    		end
		  end
      return networks
	  end

	def existing_networks
		{facebook: false, twitter: false, google_oauth2: false}
	end

	def get_user_networks (user)
		networks = []
		user.social_networks.select("provider").each do |network|
			networks << network.provider
		end
		return networks
	end

end

app/helpers/users_helper.rb
module UsersHelper
	def user_sign_up(id)
		User.where("id=?","id").update_attributes(signed_up: true)
	end

	def user_unsign_up
		current_user.update_attributes(signed_up: false, encrypted_password:"")
	end

	def user_signed_up?(email)
		User.find_by!("email=? AND signed_up=?", "email", true).present?
		rescue ActiveRecord::RecordNotFound
	    	return false
	end
end

app/views/users/shared/_edit.html.erb
<h2 class="bday-style form-text-title">Perfil</h2>

<div class="col-xs-12">
<%= form_for(resource, as: resource_name, url: edit_user_path(resource_name), html: { method: :put}) do |f| %>

  <div class="form-group form-group-sm margin-bottom">
    <%= f.label :Nombre, class:"form-text-label" %>
    <%= f.text_field :name, autofocus: true, class:"form-control form-text-input" %>
  </div>
  <div class="form-group form-group-sm margin-bottom">
    <%= f.label :Apellidos, class:"form-text-label" %>
    <%= f.text_field :surname, autofocus: true, class:"form-control form-text-input" %>
  </div>
  <div class="form-group form-group-sm margin-bottom">
    <%= f.label :email, class:"form-text-label" %>
    <%= f.email_field :email, autofocus: true, class:"form-control form-text-input" %>
  </div>
  <div class="form-group form-group-sm margin-bottom">
    <%= f.label :Cumpleaños, class:"form-text-label" %>
    <%= f.date_field :bday, autofocus: true, class:"form-control form-text-input" %>
  </div>
  <div class="form-group form-group-sm margin-bottom">
    <%= f.label :Ciudad, class:"form-text-label" %>
    <%= f.text_field :city, autofocus: true, class:"form-control form-text-input" %>
  </div>
  <div class="form-group form-group-sm margin-bottom">
    <%= f.label :País, class:"form-text-label" %>
    <%= f.text_field :country, autofocus: true, class:"form-control form-text-input" %>
  </div>
  <div class="form-group form-group-sm margin-bottom">
    <%= f.label :Idioma, class:"form-text-label" %>
    <%= f.text_field :language, autofocus: true, class:"form-control form-text-input" %>
  </div>
  <div class="form-group form-group-sm margin-bottom">
    <%= f.label :Género, class:"form-text-label" %>
    <%= f.select :gender, [['Hombre',"m"],['Mujer',"f"],['Indefinido',"u"]] %>
  </div>
</div>
<%= render "users/shared/profile_networks" %>
  <div class="row max-width no-margin">
      <div class="col-xs-8 no-padding">   
          <div class="col-xs-offset-1 col-xs-11 no-padding margin-top">
          <%= link_to 'Modificar contraseña', edit_user_registration_path %>
          </div>    
      </div>
      <div class="col-xs-4 right no-padding">
        <div class="actions right">
          <%= f.submit "Actualizar", class:"btn btn-primary right" %>
        </div>
      </div>
    </div>
  <% end %>

  
<div class="col-xs-12"> 
  <div class="row">
    <div class="col-xs-12">
      <span class="baja-label form-text-label">¿No estás content@?
      <%= link_to "Dar de baja", registration_path(resource_name), data: { confirm: "¿Estás segur@?" }, method: :delete, class:"baja" %></span>
    </div>
  </div>
</div>

app/views/users/shared/_edit_relationship.html.erb
<div class="modal fade" id="edit_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header modal-header-box">
        <button class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
        <h3 class="modal-title bday-style form-text-title">
        Editar
        </h3>
      </div><!-- .modal-header -->

      <div class="modal-body">
      <%= form_for(@relationship, url: relationships_path(), html: { method: :put, class:"edit-form" }) do |rel| %>
        <section class="modal-max-width">
        
          <div class="col-xs-2">
            <%=image_tag("", class:"img-circle img-responsive avatar-img edit-img") %>
          </div>
           
          <div class="col-xs-8 no-padding-left left">
            <h4 class:"max-width">
              <%=rel.text_field :nickname, class:"edit-nickname form-control form-text-input"%>
            </h4>
          </div>
      
          <section class="row">

            <div class="col-xs-12 left margin-top">
              <span class="info-label"><%= rel.label :"Email :" %></span>
              <span class="info-field"><%= rel.text_field :email, autofocus: true, class:"edit-email form-control form-text-input"%></span>
            </div>
            <div class="col-xs-12 left">
              <span class="info-label"><%= rel.label :"Bday :" %></span>
              <span class="info-field"><%= rel.date_select :send_date, discard_year: true, autofocus: true, class:"edit-bday" %></span>
            </div>

            <%= rel.fields_for :messages, @message do |f| %>

              <div class="col-xs-12 left">
                <h6 class="no-margin"> 
                  <%= f.check_box :send_email, value: f.object.send_email, class: "checkbox_inline edit-mail"%>
                  Email
                  
                  
                  <%= f.check_box :send_fb, class: "checkbox_inline edit-fb"%>
                    Facebook
                  
                  <%= f.check_box :send_tw, class: "checkbox_inline edit-tw"%>
                    Twitter    
                  
                  <%= f.check_box :send_gg, class: "checkbox_inline edit-gg"%>
                    Google    
                </h6>
              </div>
              <div class="col-xs-12 left margin-top">
                <span class="info-label"><%= f.label :"Mensaje :" %></span><br>
                <%= f.text_area :message, class: "form-control edit-message", rows:"3",  autofocus: true %>
              </div>
              
              <div class="col-xs-4 left">
                <div class="left">
                  <%= rel.check_box :send_message, class: "checkbox_inline edit-send"%>
                  <span class="info-label">Enviar</span>
                </div>
              </div>

            <% end %>
            </section>
          
      </div><!-- .modal-body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
        <% end %>
      </div>
    </div><!-- .modal-content -->
  </div><!-- .modal-dialog -->
</div><!-- .modal -->

app/views/users/shared/_history.html.erb
<h2 class="bday-style form-text-title">Historial de mensajes</h2>

<%= form_for(resource, as: resource_name, url: user_index_path(resource_name), html: { method: :get }) do |user| %>

  <%= user.fields_for :relationships do |rel| %>
  	<%= rel.fields_for :messages do |message| %>
		<% if message.object.message_sent %>

  	<!-- Here are the parameters for the accordion -->
		  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
		  <div class="panel panel-default">
		    <div class="panel-heading" role="tab" id="headingTwo">
		      <h4 class="panel-title">
		        <a role="button" data-toggle="collapse" data-parent="#accordion" href=<%="#m#{message.object.id}"%> aria-expanded="false" aria-controls="collapseOne">
		          <%= message.object.updated_at %>: <%=rel.object.nickname %>
		        </a>
		      </h4>
		    </div>
		    <div id=<%="m#{message.object.id}"%> class="panel-collapse collapse accordion-margins" role="tabpanel" aria-labelledby="headingTwo">
    
    <!-- Here begins the form -->
    		<section class="row">
   
	        <div class="col-xs-12 left margin-top">
	          <span class="info-label"><%= message.label :"Mensaje :" %></span>
	          <span class="info-field"><%= message.object.message%></span>
	        </div>
	                
      		</section>
   
	    	
	<!-- Here is closed the accordion -->
				</div>
			</div>
		</div>
	<!-- Up to here -->
      	<% end %>
    <% end %>  
    <% end %>
  <% end %>

app/views/users/shared/_links.html.erb
<div class="col-xs-12 max-width social-access">
	<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
	  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
	<% end -%>

	<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
	  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
	<% end -%>

	
	<%- if devise_mapping.omniauthable? %>
	  <%- resource_class.omniauth_providers.each do |provider| %>
			<%  case provider
					when :facebook %>
					<div class="col-xs-offset-1 col-xs-3 max-height">
						<%=link_to omniauth_authorize_path(resource_name, provider) do %> 
							<div class="log-icon", id="facebook-f"></div>
						<% end %>
					</div>
				 
				 <% when :twitter %>
				 	<div class="col-xs-3 max-height">
				 		<%=link_to omniauth_authorize_path(resource_name, provider) do %> 
							<div class="log-icon", id="twitter-bird"></div>
						<% end %>
					</div>
					
				 <% when :google_oauth2 %>
					 <div class="col-xs-3 max-height">
					 	<%=link_to omniauth_authorize_path(resource_name, provider) do %> 
							<div class="log-icon", id="google-g"></div>
						<% end %>
					</div>
					
	    	<% end %>
	  	<% end %>
	<% end %>
</div>

app/views/users/shared/_new_relationship.html.erb
<div class="modal fade" id="add_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header modal-header-box">
        <button class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
        <h3 class="modal-title bday-style form-text-title">
        Añadir contacto
        </h3>
      </div><!-- .modal-header -->

      <div class="modal-body">
        <%= form_for(@relationship, url: relationships_path(@relationship), html: { method: :post }) do |rel| %>

        <section class="modal-max-width">

          <div class="form-group form-group-sm margin-bottom">
          <%= rel.label :"Nombre :", class:"form-text-label" %>
              <%= rel.text_field :nickname, autofocus: true, class:"form-control form-text-input" %>        
          </div>
          <div class="form-group form-group-sm margin-bottom">
          <%= rel.label :"Email :", class:"form-text-label" %>
              <%= rel.text_field :email, autofocus: true, class:"form-control form-text-input" %>
          </div>
          <div class="form-group form-group-sm margin-bottom">
              <%= rel.label :"Cumpleaños :", class:"form-text-label" %>
               <%= rel.date_select :send_date, discard_year:true, autofocus: true %>
          </div>
        </section>      
        
      </div><!-- .modal-body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Crear contacto</button>
        <% end %>
      </div>
    </div><!-- .modal-content -->
  </div><!-- .modal-dialog -->
</div><!-- .modal -->

app/views/users/shared/_profile_networks.html.erb
<div class="col-xs-12 max-width social-access">
	
	<div class="col-xs-offset-1 col-xs-3 max-height">
		<%=link_to user_omniauth_authorize_path(:facebook) do %> 
			<div class="log-icon", id="facebook-f"></div>
		<% end %>
	</div>
 
 
 	<div class="col-xs-3 max-height">
 		<%=link_to user_omniauth_authorize_path(:twitter) do %> 
			<div class="log-icon", id="twitter-bird"></div>
		<% end %>

	</div>
	

	 <div class="col-xs-3 max-height">
	 	<%=link_to user_omniauth_authorize_path(:google_oauth2) do %> 
			<div class="log-icon", id="google-g"></div>
		<% end %>
	</div>
					
</div>

app/views/users/shared/_relationships.html.erb
<h2 class="bday-style form-text-title">Contactos</h2>

<%  
  fb_status = @user_active_networks[:facebook]
  tw_status = @user_active_networks[:twitter]
  gg_status = @user_active_networks[:google_oauth2]
%>

<%= form_for(resource, as: resource_name, url: user_index_path(resource_name), html: { method: :get }) do |user| %>

  <%= user.fields_for :relationships do |rel| %>

  <!-- Here are the parameters -->
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title form-text-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href=<%="#r#{rel.object.id}"%> aria-expanded="false" aria-controls="collapseOne" class="margin-bottom">
          <%= rel.object.nickname %>
        </a>
      </h4>
    </div>
    <div id=<%="r#{rel.object.id}"%> class="panel-collapse collapse accordion-margins" role="tabpanel" aria-labelledby="headingOne">
    
    <!-- Here begins the form -->
    <section class="row">

      <div class="col-xs-3">
        <% if rel.object.picture.present?
              img_url = rel.object.picture
            else
              img_url = "/images/avatar.svg"
            end %>

        <%=image_tag("#{img_url}", class:"img-circle img-responsive avatar-img") %>
           
      </div>
      <div class="col-xs-9 no-padding-left left">
        <h4 class:"max-width"><%=rel.object.nickname%></h4>
      </div>
    </section>
    
    <section class="row">

      <div class="col-xs-12 left margin-top">
          <span class="info-label"><%= rel.label :"Email :" %></span>
          <span class="info-field"><%= rel.object.email%></span>
      </div>
      <div class="col-xs-12 left">
        <span class="info-label"><%= rel.label :"Bday :" %></span>
        <span class="info-field">
          <% if rel.object.send_date.present? %>
            <%= rel.object.send_date.day %> de <%= @months[rel.object.send_date.month]%>
          <% end %>
        </span>
      </div>

    <%= rel.fields_for :messages do |f| %>
      
      <% if not f.object.message_sent %>
      <div class="col-xs-12 left">
      <h6 class="no-margin"> 
        <% if f.object.send_email %>
          <span class="glyphicon glyphicon-ok" id="correct-glyphicon"></span>
        <% else %>
          <span class="glyphicon glyphicon-remove" id = "wrong-glyphicon"></span>
        <% end %>
        Email


        <% if f.object.send_fb %>
          <div class="glyphicon glyphicon-ok" id="correct-glyphicon"></div>
          Facebook
        <% else %>
          <div class="glyphicon glyphicon-remove" id = "wrong-glyphicon"></div>
          Facebook
        <% end %>


        <% if f.object.send_tw %>
          <div class="glyphicon glyphicon-ok" id="correct-glyphicon"></div>
          Twitter    
        <% else %>
          <div class="glyphicon glyphicon-remove" id = "wrong-glyphicon"></div>
          Twitter
        <% end %>


        <% if f.object.send_gg %>
          <div class="glyphicon glyphicon-ok" id="correct-glyphicon"></div>
          Google    
        <% else %>
          <div class="glyphicon glyphicon-remove" id = "wrong-glyphicon"></div>
          Google
        <% end %>
      </h6>
      </div>
        <div class="col-xs-12 left margin-top">
          <span class="info-label"><%= f.label :"Mensaje :" %></span><br>
          <span class="info-field"><%= f.object.message%></span>
        </div>
        
        <div class="col-xs-6 no-margin">
        <%= content_tag "div", class:"btn btn-primary edit_modal margin-bottom", type:"button", 'data-target': "#edit_modal", 'data-toggle': "modal", data: {relationship: rel.object.attributes, message: f.object.attributes, fbstatus: fb_status, twstatus: tw_status, ggstatus: gg_status } do %> Editar <% end %> 
        <%= link_to button_tag('Enviar ahora', class: 'btn btn-success margin-bottom'), relationship_message_now_path(relationship_id: rel.object.id, message_id: f.object.id), method: :put%>

        </div>

        <div class="col-xs-offset-2 col-xs-4">
           <div class="right">
           <% if rel.object.send_message %>
              <div class="glyphicon glyphicon-ok" id="correct-glyphicon"></div>
           <% else %>
              <div class="glyphicon glyphicon-remove" id = "wrong-glyphicon"></div>
           <% end %>
              <span class="info-label">Enviar</span>
           </div>
        </div>
      </section>
         
      <section class="margin-bottom">
      <%= link_to 'Eliminar contacto',relationships_path(relationship_id: rel.object.id), method: :delete, id:"love", class:"margin-bottom"%> 
      </section>
      <% end %>
    <% end %>  
    <!-- Here is closed the accordion -->
        </div>
      </div>
    </div>
    <!-- Up to here -->
    <% end %>
    <div class="row max-space" >
      <div class="col-xs-9 max-height">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add_modal">Añadir contacto</button>
      </div>

      <div class="col-xs-3 max-height right">
        <%=link_to user_messages_path(user_id: user.object.id), method: :put do %> 
              <button type="button" class="btn btn-success right">Enviar a todos</button>
          <% end %>
      </div>      
      <% if tw_status %>
        <div class="col-xs-3 max-height">
            <%=link_to twitter_friends_path(user_id: user.object.id), method: :put do %> 
              <div class="friends-icon", id="twitter-bird"></div>
            <% end %>
          </div>
      <% end %>    
    </div>

  <% end %>
<%=render partial: "users/shared/new_relationship", locals: {user_active_networks: @user_active_networks} %>

<%=render partial: "users/shared/edit_relationship", locals: {user_active_networks: @user_active_networks} %>