config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  root to: 'site#index'
  devise_for :users, controllers: {passwords: "users/passwords", sessions: "users/sessions", registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/users/index', to: 'users#index', as: "user_index"
  get '/users/edit_profile', to: 'users#edit', as: "edit_user"
  patch '/users/edit_profile', to: 'users#update', as: ""
  put '/users/edit_profile', to: 'users#update', as: ""
  resources :relationships, only: [:create]
  patch '/relationships', to: 'relationships#update', as: ""
  put '/relationships', to: 'relationships#update', as: ""
  delete '/relationships', to: 'relationships#destroy', as: ""
  
  put '/relationships/message_now', to: 'relationships#message_now', as: "relationship_message_now"
  patch '/relationships/message_now', to: 'relationships#message_now', as: ""

  put '/relationships/twitter_friends', to: 'relationships#twitter_friends', as: "twitter_friends"
  patch '/relationships/twitter_friends', to: 'relationships#twitter_friends', as: ""

  put '/relationships/user_messages', to: 'relationships#user_messages', as: "user_messages"
  patch '/relationships/user_message', to: 'relationships#user_messages', as: ""

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :user
  	belongs_to :relationship, class_name: "User"
  	has_many :messages
  	accepts_nested_attributes_for :messages

  	def self.find_or_create(relationship)
  		Relationship.find_or_create_by(relationship).id
  	end

  	def self.relationship_exists?(user_id, relationship_id)
  		Relationship.find_by!(user_id: user_id, relationship_id: relationship_id).present?
    	rescue ActiveRecord::RecordNotFound
      		return false
  	end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :authenticate_user!
	layout "users"

	# def index
	# 	@user_active_networks = get_user_active_networks(current_user)
	# end

	def create
		name = relationship_params[:nickname].split[0] || ""
      	sirname = relationship_params[:nickname].split[1..-1].join(" ") || "" 
      	email = relationship_params[:email]
      	id = User.persona_find_or_create(nil, email, name, sirname)

      	if Relationship.relationship_exists?(current_user.id,id)
      		flash[:alert] = "Ya tenías a este contacto"
      		render relationships_path

      	else
      		rel = relationship_params.clone
      		rel[:user_id]=current_user.id
      		rel[:relationship_id]=id
          rel=clean_date(rel)
      		rel_id = Relationship.find_or_create(rel)
      		if Message.create(relationship_id: rel_id)
       			redirect_to user_index_path
      		else
      			flash[:alert] = "Oops, there was a problem creating your contact. Please try again."
      			render nothing: true
      		end
      	end
	end

	# def new
	# 	@relationship = Relationship.new
	# end

	def update
		update_successful = true
		[form_for_relationship_params].each do |relationship|
      relationship=clean_date(relationship)
			if not rel_find_by_id(form_for_relationship_id).update(rel_update_params(relationship)) or not msge(form_for_relationship_message_id).update(msge_update_params(relationship))
				update_successful = false
			end
		end
		
		if update_successful
			flash[:notice] = "Se ha guardado la información correctamente"
			redirect_to user_index_path
		else
			flash[:alert] = "Ups, ha habido algún problema al guardar la información"
      redirect_to user_index_path
		end
	end

  def destroy
    relationship = Relationship.find_by("id=?",params[:relationship_id])
    if relationship.persisted?
      relationship.destroy
      redirect_to user_index_path
    else
      flash[:alert] = "Ups, ha habido algún problema al guardar la información"
      redirect_to user_index_path
    end
  end

  def message_now
    relationship = Relationship.find_by("id=?",params[:relationship_id])
    message = Message.find_by("id=?",params[:message_id])
    if message.persisted? and relationship.persisted?
      if message.send_email or message.send_fb or message.send_tw or message.send_gg
        DeliverMessage.perform_async(relationship.id, message.id)
        flash[:notice] = "Se ha enviado tu mensaje correctamente"
      else
        flash[:alert] = "Tienes que seleccionar un método de envío para poder mandar el mensaje"
      end
      redirect_to user_index_path
    else
        flash[:alert] = "Ups, ha habido algún problema al guardar la información"
        redirect_to user_index_path
    end

  end

  def twitter_friends
    user = User.find_by("id=?",params[:user_id])
    if current_user == user
      TwitterFriends.perform_async(current_user.id)
      flash[:notice] = "Estamos cargando tus contactos, en breve aparecerán en tu cuenta"
    else
      flash[:alert] = "Ups, parece que ha habido algún problema al solicitar tus contactos. Por favor, vuelve a intentarlo en unos minutos"
    end
    redirect_to user_index_path
  end

  def user_messages
    user = User.find_by("id=?",params[:user_id])
    if current_user == user
      AutomaticallyDeliverUserMessages.perform_async(current_user.id)
      flash[:notice] = "Estamos enviando tus mensajes. Gracias por tu paciencia"
    else
      flash[:alert] = "Ups, parece que ha habido algún problema. Vuelve a intentarlo en unos minutos"
    end
    redirect_to user_index_path
  end
	
private

    def relationship_params
      params.require(:relationship).permit(:nickname, :email, :send_date)
    end

    def form_for_relationship_params
      params.require(:relationship).permit(:id, :nickname, :email, :"send_date(1i)", :"send_date(2i)", :"send_date(3i)", :send_message, messages_attributes: [:message, :send_email, :send_fb, :send_tw, :send_gg, :id])
    end

    def form_for_relationship_id
      params.require(:relationship_id)
    end

    def form_for_relationship_message_id
      params.require(:message_id)
    end

    
    def clean_date(relationship)
      year = relationship.delete("send_date(1i)").to_i || Date.today.year
      month = relationship.delete("send_date(2i)").to_i || Date.today.month
      day = relationship.delete("send_date(3i)").to_i || Date.today.day
      relationship[:send_date]=Date.new(year, month, day)

      return relationship
    end


    def rel_find_by_id(relationship_id)
    	Relationship.find_by("id=?",relationship_id)
    end

    def rel_update_params(relationship)
    	rel = relationship.clone
    	rel.delete("id")
    	rel.delete("messages_attributes")
    	return rel
    end

    def msge(message_id)
		  Message.find_by("id=?", message_id)
    end

    def msge_update_params(relationship)
    	rel = relationship.clone
    	rel[:messages_attributes].values.each do |value|
        value.delete("id")
        if value.present?
          message = value
          return message
        end
      end
    end




 #    def get_user_active_networks(user)
 #    	networks = existing_networks
 #    	user_networks = get_user_networks (user)
 #    	networks.each do |network,value|
 #    		if user_networks.include?(network.to_s)
 #    			networks[network]=true    		
 #    		end
	# 	  end
 #      return networks
	#   end

	# def existing_networks
	# 	{facebook: false, twitter: false, google_oauth2: false}
	# end

	# def get_user_networks (user)
	# 	networks = []
	# 	user.social_networks.select("provider").each do |network|
	# 		networks << network.provider
	# 	end
	# 	return networks
	# end

end	

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_message_form.html.erb
<%  
  fb_status = user_active_networks[:facebook]
  tw_status = user_active_networks[:twitter]
  gg_status = user_active_networks[:google_oauth2]
%>

<%= form_for(resource, as: resource_name, url: relationships_path(resource_name), html: { method: :put }) do |user| %>

  <%= user.fields_for :relationships do |rel| %>
    <section>
      <h4><%=rel.object.nickname%></h4>
    </section>
    
    <section>
        <%= rel.label :Email %><br>
        <%= rel.text_field :email, autofocus: true %>
    </section>
    
    <section>
      <%= rel.fields_for :messages do |f| %>
      <% if not f.object.message_sent %> 

        <% if rel.object.email.present? %>
          <%= f.check_box :send_email, class: "checkbox_inline"%>
          Email
        <% else %>
          <%= f.check_box :send_email, class: "checkbox_inline", disabled: true%>
          Email
        <% end %>


        <% if fb_status and rel.object.fb_connected %>
          <%= f.check_box :send_fb, class: "checkbox_inline"%>
          Facebook
        <% else %>
          <%= f.check_box :send_fb, class: "checkbox_inline", disabled: true%>
          Facebook
        <% end %>


        <% if tw_status and rel.object.tw_connected %>
          <%= f.check_box :send_tw, class: "checkbox_inline"%>
          Twitter    
        <% else %>
          <%= f.check_box :send_tw, class: "checkbox_inline", disabled: true%>
          Twitter
        <% end %>


        <% if gg_status and rel.object.gg_connected %>
          <%= f.check_box :send_gg, class: "checkbox_inline"%>
          Google    
        <% else %>
          <%= f.check_box :send_gg, class: "checkbox_inline", disabled: true%>
          Google
        <% end %>

        <div>
          <%= f.label :"Mensaje:" %><br>
          <%= f.text_area :message, class: "form-control", rows:"3",  autofocus: true %>
        </div>
      <% end %>
    <% end %>  

        <div class="actions">
            <%= rel.submit "Guardar" %>
        </div>
      
    <% end %>
    <div class="actions">
      <%= user.submit "Guardar todo" %>
    </div>
  <% end %>

app/views/relationships/_relationships_form.html.erb
<%  
  fb_status = user_active_networks[:facebook]
  tw_status = user_active_networks[:twitter]
  gg_status = user_active_networks[:google_oauth2]
%>

<%= button_to 'Añadir', new_relationship_path, :method => 'get', class: 'btn btn-default btn-sm tpnt_button pull-left'%>
<div>
<%= form_for(resource, as: resource_name, url: relationships_path(resource_name), html: { method: :put }) do |user| %>

  <section>
    <div class="actions">
      <%= user.submit "Guardar" %>
    </div>
  </section>

  <%= user.fields_for :relationships do |rel| %>
    <section>
      <h4><%=rel.text_field :nickname%></h4>
    </section>
    
    <section>
        <%= rel.label :Email %>
        <%= rel.text_field :email, autofocus: true %>
        <%= rel.label :Birthday %>
        <%= rel.date_select :send_date, discard_year: true, autofocus: true %>
    </section>
    
    <section>
      <%= rel.fields_for :messages do |f| %>
      <% if not f.object.message_sent %> 

        <% if rel.object.email.present? %>
          <%= f.check_box :send_email, class: "checkbox_inline"%>
          Email
        <% else %>
          <%= f.check_box :send_email, class: "checkbox_inline", disabled: true%>
          Email
        <% end %>


        <% if fb_status and rel.object.fb_connected %>
          <%= f.check_box :send_fb, class: "checkbox_inline"%>
          Facebook
        <% else %>
          <%= f.check_box :send_fb, class: "checkbox_inline", disabled: true%>
          Facebook
        <% end %>


        <% if tw_status and rel.object.tw_connected %>
          <%= f.check_box :send_tw, class: "checkbox_inline"%>
          Twitter    
        <% else %>
          <%= f.check_box :send_tw, class: "checkbox_inline", disabled: true%>
          Twitter
        <% end %>


        <% if gg_status and rel.object.gg_connected %>
          <%= f.check_box :send_gg, class: "checkbox_inline"%>
          Google    
        <% else %>
          <%= f.check_box :send_gg, class: "checkbox_inline", disabled: true%>
          Google
        <% end %>

        <div>
          <%= f.label :"Mensaje:" %><br>
          <%= f.text_area :message, class: "form-control", rows:"3",  autofocus: true %>         
        </div>

      <% end %>
      Send<%= rel.check_box :send_message, class: "checkbox_inline"%> 
    <% end %>  
    </section>
      
    <% end %>
    <div class="actions">
      <%= user.submit "Guardar" %>
    </div>
  <% end %>
  </div>